2020-03-02 01:20:15,318 WARN [http-nio-8887-exec-1] o.a.c.u.SessionIdGeneratorBase [DirectJDKLog.java:173] Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [299] milliseconds.
2020-03-02 02:36:29,336 WARN [http-nio-8887-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2020-03-02 02:36:29,455 WARN [http-nio-8887-exec-2] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2020-03-02 02:36:29,495 WARN [http-nio-8887-exec-8] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [java.lang.IllegalStateException: Cannot connect, Event executor group is terminated.]
2020-03-02 06:39:41,885 WARN [restartedMain] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [AbstractApplicationContext.java:558] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is java.lang.IllegalStateException: Topic(s) [comment, follow, like] is/are not present and missingTopicsFatal is true
2020-03-02 06:45:27,404 WARN [restartedMain] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [AbstractApplicationContext.java:558] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is java.lang.IllegalStateException: Topic(s) [comment, follow, like] is/are not present and missingTopicsFatal is true
2020-03-02 07:34:54,251 WARN [restartedMain] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [AbstractApplicationContext.java:558] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is java.lang.IllegalStateException: Topic(s) [comment, follow, like] is/are not present and missingTopicsFatal is true
2020-03-02 07:37:05,596 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.NetworkClient [NetworkClient.java:1051] [Consumer clientId=consumer-1, groupId=community-consumer-group] Error while fetching metadata with correlation id 2 : {like=LEADER_NOT_AVAILABLE, comment=LEADER_NOT_AVAILABLE, follow=LEADER_NOT_AVAILABLE}
2020-03-02 07:37:05,837 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.NetworkClient [NetworkClient.java:1051] [Consumer clientId=consumer-1, groupId=community-consumer-group] Error while fetching metadata with correlation id 4 : {comment=LEADER_NOT_AVAILABLE, follow=LEADER_NOT_AVAILABLE}
2020-03-02 07:37:06,019 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.NetworkClient [NetworkClient.java:1051] [Consumer clientId=consumer-1, groupId=community-consumer-group] Error while fetching metadata with correlation id 6 : {follow=LEADER_NOT_AVAILABLE}
2020-03-02 20:32:13,877 WARN [http-nio-8887-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [java.lang.NullPointerException]
2020-03-02 21:28:33,185 WARN [HikariPool-1 housekeeper] c.z.h.p.HikariPool [HikariPool.java:779] HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=52m41s868ms175Âµs834ns).
2020-03-02 21:28:33,225 WARN [http-nio-8887-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [java.lang.NullPointerException]
2020-03-02 21:28:33,311 WARN [http-nio-8887-exec-6] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2020-03-02 21:28:33,423 WARN [http-nio-8887-exec-7] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2020-03-02 21:29:13,343 WARN [http-nio-8887-exec-2] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [java.lang.NullPointerException]
2020-03-02 21:29:55,030 WARN [http-nio-8887-exec-7] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [java.lang.NullPointerException]
2020-03-02 21:32:14,619 WARN [http-nio-8887-exec-4] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [java.lang.NullPointerException]
2020-03-02 21:41:10,245 WARN [http-nio-8887-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'createTime' in 'order clause'
### The error may exist in file [D:\IDEAWorkSpace\finalcommunity\target\classes\mapper\message-mapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select                   id,from_id,to_id,conversation_id,content,status,create_time               from message         where status != 2         and from_id = 1         and to_id = ?         and conversation_Id = ?         order by createTime desc         limit ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'createTime' in 'order clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'createTime' in 'order clause']
2020-03-02 21:41:24,931 WARN [http-nio-8887-exec-6] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:199] Resolved [org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'createTime' in 'order clause'
### The error may exist in file [D:\IDEAWorkSpace\finalcommunity\target\classes\mapper\message-mapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select                   id,from_id,to_id,conversation_id,content,status,create_time               from message         where status != 2         and from_id = 1         and to_id = ?         and conversation_Id = ?         order by createTime desc         limit ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'createTime' in 'order clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'createTime' in 'order clause']
